org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.242
loader_version_range=[1,)

mod_id=offhandcombat
mod_name=Off Hand Combat
mod_license=MIT
mod_version=1.0.0-neoforge.1
mod_group_id=dev.nekomario.offhandcombat
